# Generated by Django 5.1.6 on 2025-02-12 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='item_parice',
            new_name='item_price',
        ),
    ]
