# Generated by Django 5.1.6 on 2025-02-13 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_rename_item_parice_item_item_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://imgs.search.brave.com/Tjhi7PMxaRtFlKw9I3Nr5x2Dm8jyw0y3z5aVH3Zjpog/rs:fit:500:0:0:0/g:ce/aHR0cHM6Ly9tZWRp/YS5nZXR0eWltYWdl/cy5jb20vaWQvNDcx/NDU2MDYxL3Bob3Rv/L2hhbWJ1cmdlci5q/cGc_cz02MTJ4NjEy/Jnc9MCZrPTIwJmM9/SjJEV2R4TU51M1A5/NkJEQ2J1TWRJM0R1/TG8zMjRzNEJBaVZD/dXExUDQzZz0', max_length=500),
        ),
    ]
